#!/usr/bin/env bash

file=$1

## File is javascript, run eslint
OUT=`git show :$file | eslint --stdin-filename "$file" --stdin 1>&2`
if [ $? != 0 ]
then
    echo "REJECT: $file fails eslint"
    echo $OUT
    exit 1
fi
